POST http://localhost:3003/api/blogs HTTP/ 1.1
Content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBlcnNvbiIsImlkIjoiNjFkODljNGE2MGZjOTE4YjQxYmY1NTIzIiwiaWF0IjoxNjQxNTg1NzUzfQ.mCkla2K0gtrCW8rEpaCadwvXTteHVSqVqONpEJJEbVs

{
    "title": "TestBlog5",
    "author": "TestAuthor2",
    "url": "testblog2",
    "likes": 3
} 